class Canon{
    constructor(x,y,width,height,angle){
this.x=x, 
this.y=y,
this.width=width,
this.height=height,
this.angle=angle
this.canon_Image=loadImage("assets/canon.png")
this.cannon_Base=loadImage("assets/cannonBase.png")
    }
    display(){
        push()
        //rectMode(CENTER)
        imageMode(CENTER)
        //rect(this.x,this.y,this.width,this.height,this.angle)
        image(this.canon_Image,this.x,this.y,this.width,this.height)
        pop()
        //rect(70,20,200,200)
        image(this.cannon_Base,70,20,200,200)
        noFill()
    }
}